import type { Edge, Node } from "@xyflow/react";
import { FlowDiagram } from "./FlowWrapper";

const nodes: Node[] = [
	{
		id: "req",
		position: { x: 280, y: 0 },
		data: { label: "Incoming Request" },
		type: "input",
		style: {
			background: "#3b82f6",
			color: "#fff",
			border: "none",
			borderRadius: 8,
			fontWeight: 600,
			fontSize: 12,
			padding: "10px 20px",
		},
	},
	{
		id: "router-cache",
		position: { x: 250, y: 90 },
		data: { label: "Router Cache (browser)" },
		style: {
			background: "#a855f720",
			border: "1px solid #a855f760",
			borderRadius: 8,
			fontSize: 11,
			fontWeight: 600,
			width: 200,
			textAlign: "center" as const,
		},
	},
	{
		id: "router-hit",
		position: { x: 520, y: 90 },
		data: { label: "✓ HIT → Instant Response" },
		style: {
			background: "#22c55e20",
			border: "1px solid #22c55e60",
			borderRadius: 20,
			fontSize: 10,
			fontWeight: 600,
			width: 170,
			textAlign: "center" as const,
		},
	},
	{
		id: "full-route",
		position: { x: 250, y: 180 },
		data: { label: "Full Route Cache (server FS)" },
		style: {
			background: "#eab30820",
			border: "1px solid #eab30860",
			borderRadius: 8,
			fontSize: 11,
			fontWeight: 600,
			width: 220,
			textAlign: "center" as const,
		},
	},
	{
		id: "full-route-hit",
		position: { x: 540, y: 180 },
		data: { label: "✓ HIT → Fast Response" },
		style: {
			background: "#22c55e20",
			border: "1px solid #22c55e60",
			borderRadius: 20,
			fontSize: 10,
			fontWeight: 600,
			width: 160,
			textAlign: "center" as const,
		},
	},
	{
		id: "rsc-render",
		position: { x: 250, y: 275 },
		data: { label: "React Server Component Render" },
		style: {
			background: "#22c55e",
			color: "#fff",
			border: "none",
			borderRadius: 8,
			fontWeight: 600,
			fontSize: 12,
			width: 250,
			textAlign: "center" as const,
		},
	},
	{
		id: "fetch",
		position: { x: 140, y: 370 },
		data: { label: "fetch(url) / db query" },
		style: {
			background: "#06b6d420",
			border: "1px solid #06b6d460",
			borderRadius: 8,
			fontSize: 11,
			width: 170,
			textAlign: "center" as const,
		},
	},
	{
		id: "data-cache",
		position: { x: 140, y: 455 },
		data: { label: "Data Cache (persistent)" },
		style: {
			background: "#3b82f620",
			border: "1px solid #3b82f660",
			borderRadius: 8,
			fontSize: 11,
			fontWeight: 600,
			width: 180,
			textAlign: "center" as const,
		},
	},
	{
		id: "data-hit",
		position: { x: 380, y: 410 },
		data: { label: "✓ HIT → use cached data" },
		style: {
			background: "#22c55e20",
			border: "1px solid #22c55e60",
			borderRadius: 20,
			fontSize: 10,
			fontWeight: 600,
			width: 160,
			textAlign: "center" as const,
		},
	},
	{
		id: "req-memo",
		position: { x: 140, y: 545 },
		data: { label: "Request Memoization\n(in-memory)" },
		style: {
			background: "#22c55e20",
			border: "1px solid #22c55e60",
			borderRadius: 8,
			fontSize: 11,
			fontWeight: 600,
			whiteSpace: "pre-line" as const,
			width: 180,
			textAlign: "center" as const,
		},
	},
	{
		id: "memo-hit",
		position: { x: 380, y: 510 },
		data: { label: "✓ HIT → deduplicated" },
		style: {
			background: "#22c55e20",
			border: "1px solid #22c55e60",
			borderRadius: 20,
			fontSize: 10,
			fontWeight: 600,
			width: 160,
			textAlign: "center" as const,
		},
	},
	{
		id: "network",
		position: { x: 140, y: 640 },
		data: { label: "Network / Database\n← actual I/O" },
		style: {
			background: "#ef444420",
			border: "1px solid #ef444460",
			borderRadius: 8,
			fontSize: 11,
			fontWeight: 600,
			whiteSpace: "pre-line" as const,
			width: 170,
			textAlign: "center" as const,
		},
	},
	{
		id: "output",
		position: { x: 250, y: 740 },
		data: {
			label:
				"Rendered RSC Payload\n→ populate Full Route Cache (if static)\n→ send to browser\n→ store in Router Cache",
		},
		type: "output",
		style: {
			background: "#f59e0b20",
			border: "1px dashed #f59e0b80",
			borderRadius: 8,
			fontSize: 10,
			whiteSpace: "pre-line" as const,
			width: 280,
			textAlign: "left" as const,
			padding: "10px 14px",
		},
	},
];

const edges: Edge[] = [
	{
		id: "e1",
		source: "req",
		target: "router-cache",
		animated: true,
		style: { stroke: "#a855f7" },
	},
	{
		id: "e2",
		source: "router-cache",
		target: "router-hit",
		label: "HIT",
		style: { stroke: "#22c55e" },
	},
	{
		id: "e3",
		source: "router-cache",
		target: "full-route",
		label: "MISS",
		style: { stroke: "#ef4444" },
	},
	{
		id: "e4",
		source: "full-route",
		target: "full-route-hit",
		label: "HIT",
		style: { stroke: "#22c55e" },
	},
	{
		id: "e5",
		source: "full-route",
		target: "rsc-render",
		label: "MISS",
		style: { stroke: "#ef4444" },
	},
	{
		id: "e6",
		source: "rsc-render",
		target: "fetch",
		style: { stroke: "#22c55e" },
	},
	{
		id: "e7",
		source: "fetch",
		target: "data-cache",
		style: { stroke: "#3b82f6" },
	},
	{
		id: "e8",
		source: "data-cache",
		target: "data-hit",
		label: "HIT",
		style: { stroke: "#22c55e" },
	},
	{
		id: "e9",
		source: "data-cache",
		target: "req-memo",
		label: "MISS",
		style: { stroke: "#ef4444" },
	},
	{
		id: "e10",
		source: "req-memo",
		target: "memo-hit",
		label: "HIT",
		style: { stroke: "#22c55e" },
	},
	{
		id: "e11",
		source: "req-memo",
		target: "network",
		label: "MISS",
		style: { stroke: "#ef4444" },
	},
	{
		id: "e12",
		source: "rsc-render",
		target: "output",
		animated: true,
		style: { stroke: "#f59e0b" },
	},
];

export function CacheInteractionFlow() {
	return <FlowDiagram edges={edges} height="860px" nodes={nodes} />;
}
