import type { Edge, Node } from "@xyflow/react";
import { FlowDiagram } from "./FlowWrapper";

const nodes: Node[] = [
	{
		id: "start",
		position: { x: 220, y: 0 },
		data: { label: "Multiple independent data needs?" },
		type: "input",
		style: {
			background: "#8b5cf6",
			color: "#fff",
			border: "none",
			borderRadius: 10,
			fontWeight: 600,
			fontSize: 11,
			width: 250,
			textAlign: "center" as const,
			padding: "10px 16px",
		},
	},
	{
		id: "yes-parallel",
		position: { x: 30, y: 90 },
		data: { label: "YES → Promise.all([\n  fetchA(), fetchB(), fetchC()\n])" },
		style: {
			background: "#22c55e20",
			border: "1px solid #22c55e60",
			borderRadius: 8,
			fontSize: 10,
			fontFamily: "monospace",
			whiteSpace: "pre-line" as const,
			width: 220,
			textAlign: "left" as const,
			padding: "8px 12px",
		},
	},
	{
		id: "depends",
		position: { x: 340, y: 90 },
		data: { label: "Request B depends on A?" },
		style: {
			background: "#f59e0b20",
			border: "1px solid #f59e0b60",
			borderRadius: 10,
			fontWeight: 600,
			fontSize: 11,
			width: 200,
			textAlign: "center" as const,
		},
	},
	{
		id: "sequential",
		position: { x: 280, y: 190 },
		data: {
			label: "YES → Sequential await\n(can you restructure for 1 round-trip?)",
		},
		style: {
			background: "#eab30820",
			border: "1px solid #eab30860",
			borderRadius: 8,
			fontSize: 10,
			whiteSpace: "pre-line" as const,
			width: 250,
			textAlign: "center" as const,
		},
	},
	{
		id: "same-fn",
		position: { x: 60, y: 260 },
		data: { label: "Same function called\nin multiple components?" },
		style: {
			background: "#3b82f620",
			border: "1px solid #3b82f660",
			borderRadius: 10,
			fontWeight: 600,
			fontSize: 11,
			whiteSpace: "pre-line" as const,
			width: 210,
			textAlign: "center" as const,
		},
	},
	{
		id: "cache",
		position: { x: 30, y: 360 },
		data: { label: "Wrap with react.cache()\n→ automatic deduplication" },
		style: {
			background: "#3b82f620",
			border: "1px solid #3b82f660",
			borderRadius: 8,
			fontSize: 10,
			whiteSpace: "pre-line" as const,
			width: 190,
			textAlign: "center" as const,
		},
	},
	{
		id: "preload-q",
		position: { x: 310, y: 310 },
		data: { label: "Start fetch before\nyou await it?" },
		style: {
			background: "#a855f720",
			border: "1px solid #a855f760",
			borderRadius: 10,
			fontWeight: 600,
			fontSize: 11,
			whiteSpace: "pre-line" as const,
			width: 170,
			textAlign: "center" as const,
		},
	},
	{
		id: "preload-pattern",
		position: { x: 290, y: 410 },
		data: { label: "Preload pattern\nvoid getX(id) to warm cache" },
		style: {
			background: "#a855f720",
			border: "1px solid #a855f760",
			borderRadius: 8,
			fontSize: 10,
			whiteSpace: "pre-line" as const,
			width: 200,
			textAlign: "center" as const,
		},
	},
	{
		id: "client-data",
		position: { x: 530, y: 310 },
		data: { label: "Client-side real-time data?\n→ React Query / SWR" },
		type: "output",
		style: {
			background: "#06b6d420",
			border: "1px solid #06b6d460",
			borderRadius: 8,
			fontSize: 10,
			whiteSpace: "pre-line" as const,
			width: 180,
			textAlign: "center" as const,
		},
	},
];

const edges: Edge[] = [
	{
		id: "e1",
		source: "start",
		target: "yes-parallel",
		label: "YES",
		style: { stroke: "#22c55e" },
	},
	{
		id: "e2",
		source: "start",
		target: "depends",
		label: "NO",
		style: { stroke: "#f59e0b" },
	},
	{
		id: "e3",
		source: "depends",
		target: "sequential",
		label: "YES",
		style: { stroke: "#eab308" },
	},
	{
		id: "e4",
		source: "depends",
		target: "same-fn",
		label: "NO",
		style: { stroke: "#3b82f6" },
	},
	{
		id: "e5",
		source: "same-fn",
		target: "cache",
		label: "YES",
		style: { stroke: "#3b82f6" },
	},
	{
		id: "e6",
		source: "same-fn",
		target: "preload-q",
		label: "NO",
		style: { stroke: "#a855f7" },
	},
	{
		id: "e7",
		source: "preload-q",
		target: "preload-pattern",
		label: "YES",
		style: { stroke: "#a855f7" },
	},
	{
		id: "e8",
		source: "preload-q",
		target: "client-data",
		label: "Client?",
		style: { stroke: "#06b6d4" },
	},
];

export function DataFetchingFlow() {
	return <FlowDiagram edges={edges} height="520px" nodes={nodes} />;
}
