import type { Edge, Node } from "@xyflow/react";
import { FlowDiagram } from "./FlowWrapper";

const nodes: Node[] = [
	{
		id: "client",
		position: { x: 250, y: 0 },
		data: { label: "Client Component\nuser interaction (click / form submit)" },
		type: "input",
		style: {
			background: "#3b82f6",
			color: "#fff",
			border: "none",
			borderRadius: 8,
			fontWeight: 600,
			fontSize: 11,
			whiteSpace: "pre-line" as const,
			width: 260,
			textAlign: "center" as const,
			padding: "10px 16px",
		},
	},
	{
		id: "transition",
		position: { x: 260, y: 110 },
		data: { label: "startTransition(() => myAction(args))" },
		style: {
			background: "#8b5cf620",
			border: "1px solid #8b5cf660",
			borderRadius: 8,
			fontSize: 11,
			fontFamily: "monospace",
			width: 280,
			textAlign: "center" as const,
		},
	},
	{
		id: "post",
		position: { x: 240, y: 200 },
		data: {
			label:
				"POST /_next/action/<signed-id>\nBody: serialised args (Flight format)",
		},
		style: {
			background: "#f59e0b20",
			border: "1px dashed #f59e0b80",
			borderRadius: 8,
			fontSize: 10,
			whiteSpace: "pre-line" as const,
			width: 270,
			textAlign: "center" as const,
			fontStyle: "italic",
		},
	},
	{
		id: "server",
		position: { x: 250, y: 310 },
		data: { label: "Next.js Server" },
		style: {
			background: "#22c55e",
			color: "#fff",
			border: "none",
			borderRadius: 8,
			fontWeight: 600,
			fontSize: 12,
			width: 200,
			textAlign: "center" as const,
		},
	},
	{
		id: "verify",
		position: { x: 200, y: 400 },
		data: { label: "Verify HMAC signature\nDeserialise args" },
		style: {
			background: "#ef444420",
			border: "1px solid #ef444460",
			borderRadius: 8,
			fontSize: 10,
			whiteSpace: "pre-line" as const,
			width: 180,
			textAlign: "center" as const,
		},
	},
	{
		id: "execute",
		position: { x: 200, y: 490 },
		data: { label: "Execute myAction()" },
		style: {
			background: "#22c55e20",
			border: "1px solid #22c55e60",
			borderRadius: 8,
			fontSize: 11,
			fontWeight: 600,
			width: 180,
			textAlign: "center" as const,
		},
	},
	{
		id: "db",
		position: { x: 440, y: 430 },
		data: { label: "Direct DB /\nservice calls" },
		style: {
			background: "#06b6d420",
			border: "1px solid #06b6d460",
			borderRadius: 8,
			fontSize: 10,
			whiteSpace: "pre-line" as const,
			width: 120,
			textAlign: "center" as const,
		},
	},
	{
		id: "revalidate",
		position: { x: 440, y: 520 },
		data: { label: "revalidatePath()\nrevalidateTag()\n→ invalidate caches" },
		style: {
			background: "#a855f720",
			border: "1px solid #a855f760",
			borderRadius: 8,
			fontSize: 10,
			whiteSpace: "pre-line" as const,
			width: 140,
			textAlign: "center" as const,
		},
	},
	{
		id: "return",
		position: { x: 230, y: 590 },
		data: { label: "Return value\n(serialised via Flight)" },
		style: {
			background: "#f59e0b20",
			border: "1px dashed #f59e0b80",
			borderRadius: 8,
			fontSize: 10,
			whiteSpace: "pre-line" as const,
			width: 200,
			textAlign: "center" as const,
			fontStyle: "italic",
		},
	},
	{
		id: "client-recv",
		position: { x: 220, y: 690 },
		data: { label: "Client receives response" },
		style: {
			background: "#3b82f6",
			color: "#fff",
			border: "none",
			borderRadius: 8,
			fontWeight: 600,
			fontSize: 12,
			width: 220,
			textAlign: "center" as const,
		},
	},
	{
		id: "update-ui",
		position: { x: 100, y: 780 },
		data: { label: "React updates UI\nwith return value" },
		style: {
			background: "#3b82f620",
			border: "1px solid #3b82f660",
			borderRadius: 8,
			fontSize: 10,
			whiteSpace: "pre-line" as const,
			width: 150,
			textAlign: "center" as const,
		},
	},
	{
		id: "refetch",
		position: { x: 280, y: 780 },
		data: { label: "Revalidated paths\nre-fetch in background" },
		style: {
			background: "#a855f720",
			border: "1px solid #a855f760",
			borderRadius: 8,
			fontSize: 10,
			whiteSpace: "pre-line" as const,
			width: 160,
			textAlign: "center" as const,
		},
	},
	{
		id: "optimistic",
		position: { x: 470, y: 780 },
		data: { label: "useOptimistic\nconfirms / reverts" },
		type: "output",
		style: {
			background: "#f59e0b20",
			border: "1px solid #f59e0b60",
			borderRadius: 8,
			fontSize: 10,
			whiteSpace: "pre-line" as const,
			width: 140,
			textAlign: "center" as const,
		},
	},
];

const edges: Edge[] = [
	{
		id: "e1",
		source: "client",
		target: "transition",
		style: { stroke: "#3b82f6" },
	},
	{
		id: "e2",
		source: "transition",
		target: "post",
		animated: true,
		style: { stroke: "#f59e0b" },
	},
	{
		id: "e3",
		source: "post",
		target: "server",
		animated: true,
		style: { stroke: "#f59e0b" },
	},
	{
		id: "e4",
		source: "server",
		target: "verify",
		style: { stroke: "#ef4444" },
	},
	{
		id: "e5",
		source: "verify",
		target: "execute",
		style: { stroke: "#22c55e" },
	},
	{
		id: "e6",
		source: "execute",
		target: "db",
		style: { stroke: "#06b6d4" },
	},
	{
		id: "e7",
		source: "execute",
		target: "revalidate",
		style: { stroke: "#a855f7" },
	},
	{
		id: "e8",
		source: "execute",
		target: "return",
		animated: true,
		style: { stroke: "#f59e0b" },
	},
	{
		id: "e9",
		source: "return",
		target: "client-recv",
		animated: true,
		style: { stroke: "#3b82f6" },
	},
	{
		id: "e10",
		source: "client-recv",
		target: "update-ui",
		style: { stroke: "#3b82f6" },
	},
	{
		id: "e11",
		source: "client-recv",
		target: "refetch",
		style: { stroke: "#a855f7" },
	},
	{
		id: "e12",
		source: "client-recv",
		target: "optimistic",
		style: { stroke: "#f59e0b" },
	},
];

export function ServerActionFlow() {
	return <FlowDiagram edges={edges} height="880px" nodes={nodes} />;
}
